---
name: Coverage Report

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install openai
          # Install other dependencies if needed

      - name: Run tests with coverage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: coverage run -m pytest

      - name: Generate coverage report
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: coverage html

      - name: Check coverage threshold
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          COVERAGE_THRESHOLD=70
          COVERAGE_PERCENTAGE=$(coverage report | grep TOTAL | awk '{print $NF}')
          if [ "$COVERAGE_PERCENTAGE" -lt "$COVERAGE_THRESHOLD" ]; then
            echo "Coverage is below the required threshold ($COVERAGE_PERCENTAGE% < $COVERAGE_THRESHOLD%)"
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
