name: Push README to Docker Hub

on:
  workflow_run:
    workflows: "Build and Push Docker Image"
    types:
      - completed
  push:
    branches:
      - main

jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/chatting-with-chatgpt
          provider: dockerhub
          short_description: 'Sample Python application for chatting with ChatGPT via API.'
          readme_file: 'README.md'